<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5qBu7xy\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5qBu7xy/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container5qBu7xy.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container5qBu7xy\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container5qBu7xy\appAppKernelProdContainer([
    'container.build_hash' => '5qBu7xy',
    'container.build_id' => 'f798779b',
    'container.build_time' => 1689116262,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5qBu7xy');
