<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKIOGMBrHlZll9q/j+X3'."\n".'FsSB6pmA+axJKPP92BNCIi5uT96kvDXFGivGV07jxCqVh0iSot1HAnSs5WEZ+/Tb'."\n".'OYZIgEk5wF2ADLcnw8ii2uiIEu8lycGhedlkWk0ibRW6HilUWXGbtrdd//nfUzzi'."\n".'eEJx3fkBCA2iHBPnOAvgJNinfxWo+lHxQumttBTSUC/DYs1V98z4R4n15N1yh5BU'."\n".'xx7yecb8lUjNZtrAnb8ttcX0hNxLe/hyZyZ6fzL0IBHEdzzj6QCJxoxjP6ZdgXhI'."\n".'idbTufCYBhLAoSSboxQt25crYmivu3lzk8WwhUphleX7TghpYbTG8k5y/QKaVANO'."\n".'awIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
