<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPYedxxF\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYedxxF/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYedxxF.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPYedxxF\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerPYedxxF\appAppKernelDevDebugContainer([
    'container.build_hash' => 'PYedxxF',
    'container.build_id' => '30d483db',
    'container.build_time' => 1689229641,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYedxxF');
